language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y libeigen3-dev libfftw3-dev

install:
  - python setup.py develop

script:
  - py.test --doctest-modules pybindcpp

