language: python
python:
    - "3.6"
    - "3.7"

addons:
  apt:
    packages: &common_packages
      - gcc-6
      - g++-6
      - libeigen3-dev
      - libfftw3-dev
    sources: &sources
      - ubuntu-toolchain-r-test

install:
    - export CC=gcc-6
    - export CXX=g++-6
    - python setup.py develop

script:
    - py.test --doctest-modules pybindcpp

